name: survival_tests
channels:
  - sebp
  - anaconda
  - defaults
dependencies:
  - blas=1.0
  - ca-certificates=2019.11.27
  - certifi=2019.11.28
  - cvxopt=1.2.3
  - cvxpy=1.0.15
  - cvxpy-base=1.0.15
  - dill=0.3.1.1
  - ecos=2.0.7.post1
  - fastcache=1.1.0
  - fftw=3.3.8
  - future=0.18.2
  - glpk=4.65
  - gmp=6.1.2
  - gsl=2.4
  - intel-openmp=2019.4
  - joblib=0.14.1
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgfortran
  - libprotobuf=3.6.0
  - metis=5.1.0
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.0
  - multiprocess=0.70.8
  - mysql-connector-c=6.1.11
  - mysql-connector-python=8.0.18
  - ncurses=6.1
  - numexpr=2.7.0
  - numpy=1.17.4
  - numpy-base=1.17.4
  - openssl=1.1.1
  - osqp=0.5.0
  - pip=19.3.1
  - protobuf=3.6.0
  - python=3.7.6
  - pyyaml=5.2
  - readline=7.0
  - scikit-learn=0.21.3
  - scikit-survival=0.11
  - scipy=1.3.1
  - scs=2.1.1.2
  - setuptools=44.0.0
  - six=1.13.0
  - sqlite=3.30.1
  - suitesparse=5.2.0
  - tbb=2019.8
  - tk=8.6.8
  - wheel=0.33.6
  - xz=5.2.4
  - yaml=0.1.7
  - zlib=1.2.11
  - pip:
    - liac-arff==2.4.0
    - pandas==0.25.3
    - python-dateutil==2.8.1
    - pytz==2019.3

