name: survival_tests
channels:
  - pytorch
  - anaconda
  - sebp
  - conda-forge
  - defaults
dependencies:
  - blas=1.0
  - ca-certificates=2020.1.1
  - certifi=2019.11.28
  - cloudpickle=1.2.2
  - cvxopt=1.2.3
  - cvxpy=1.0.15
  - cvxpy-base=1.0.15
  - cycler=0.10.0
  - decorator=4.4.1
  - dill=0.3.1.1
  - ecos=2.0.7.post1
  - fastcache=1.1.0
  - fftw=3.3.8
  - freetype=2.9.1
  - future=0.18.2
  - glpk=4.65
  - gmp=6.1.2
  - gsl=2.4
  - hyperopt=0.2.2
  - intel-openmp=2019.4
  - joblib=0.14.1
  - jpeg=9b
  - kiwisolver=1.1.0
  - libcxx
  - libcxxabi
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgfortran
  - libpng=1.6.37
  - libprotobuf=3.6.0
  - libtiff=4.1.0
  - llvm-openmp
  - matplotlib=3.1.1
  - metis=5.1.0
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.0
  - multiprocess=0.70.8
  - mysql-connector-c=6.1.11
  - mysql-connector-python=8.0.18
  - ncurses=6.1
  - networkx=2.4
  - ninja=1.9.0
  - numexpr=2.7.0
  - numpy=1.17.4
  - numpy-base=1.17.4
  - olefile=0.46
  - openssl=1.1.1d
  - osqp=0.5.0
  - patsy=0.5.1
  - pillow=7.0.0
  - pip=19.3.1
  - protobuf=3.6.0
  - pymongo=3.8.0
  - pyparsing=2.4.6
  - python=3.7.6
  - pytorch=1.4.0
  - pyyaml=5.2
  - readline=7.0
  - scikit-learn=0.21.3
  - scikit-survival=0.11
  - scipy=1.3.1
  - scs=2.1.1.2
  - seaborn=0.9.0
  - setuptools=44.0.0
  - six=1.13.0
  - sqlite=3.30.1
  - statsmodels=0.11.0
  - suitesparse=5.2.0
  - tbb=2019.8
  - tk=8.6.8
  - torchvision=0.5.0
  - tornado=6.0.3
  - tqdm=4.42.1
  - wheel=0.33.6
  - xz=5.2.4
  - yaml=0.1.7
  - zlib=1.2.11
  - zstd=1.3.7
  - pip:
    - ax-platform==0.1.9
    - botorch==0.2.1
    - gpytorch==1.0.1
    - jinja2==2.11.1
    - liac-arff==2.4.0
    - markupsafe==1.1.1
    - pandas==0.25.3
    - plotly==4.5.0
    - python-dateutil==2.8.1
    - pytz==2019.3
    - retrying==1.3.3

